### ISSUE TITLE
Become No bound request on HystrixTimer execution

### ISSUE THREAD

**Issue by horyna** [jmnarloch/hystrix-context-spring-boot-starter#3]
On HystrixTimer execution this code failed, because wrapCallable is called in new HystrixTimer thread where no RequestContextHolder is available. Or am i doing something wrong?

`java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
36
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)
35
	at my.company.hystrix.wrapper.RequestAttributeAwareCallableWrapper.wrapCallable(RequestAttributeAwareCallableWrapper.java:24)
34
	at io.jmnarloch.spring.boot.hystrix.support.HystrixContextAwareConcurrencyStrategy$CallableWrapperChain.wrapCallable(HystrixContextAwareConcurrencyStrategy.java:68)
33
	at io.jmnarloch.spring.boot.hystrix.support.HystrixContextAwareConcurrencyStrategy.wrapCallable(HystrixContextAwareConcurrencyStrategy.java:51)
32
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.<init>(HystrixContextRunnable.java:41)
31
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1150)
30
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)`

**Comment by horyna** [comment]
Aha, it seems the problem was in 1.5.12, upgraded to 1.5.18 and ewerythinks look fine
